apiVersion: v1
kind: ConfigMap
metadata:
  name: nuudel-form-submit-script
data:
  nuudel-form-submit.sh: |
    #!/bin/bash
    #
    # Purpose: Adds next week's Friday and Saturday to the specified poll
    # Helpful source for date magic: https://unix.stackexchange.com/a/274966
    # Command example: curl --data "newdate=2022-12-31&newmoment=Test&confirm_add_column=''" https://nuudel.digitalcourage.de/uwLnt3fcNUvoxIXi8IoWaV3S/admin
    #

    url=$NUUDEL_ADMIN_URL
    nextfriday="$(date -d "next fri" +%Y-%m-%d)"

    for addition in 7 8; do
      for moment in Nomi Obe; do
        date=$(date -d "$nextfriday +${addition} day" +%Y-%m-%d)
        curl --silent --output /dev/null --show-error --fail --data "newdate=$date&newmoment=$moment&confirm_add_column=''" $url
      done
    done
